### ISSUE TITLE
Missing transparency

### ISSUE THREAD

**Issue by Sami32** [gino0631/pkg#4]
Except if i missed something the textual windows transparency is not set so the background image is hidden.
Below is a sample with transparency:

![ecigb](https://user-images.githubusercontent.com/18471069/41728096-7a42f592-7565-11e8-94a5-d08b6125b462.png)

**Comment by Nadahar** [comment]
@Sami32 Are you sure that isn't a desktop setting? Also, I don't think the transparency does anything for the readability of the message...

**Comment by Sami32** [comment]
Maybe, as a Windows user i've no idea.

**Comment by Nadahar** [comment]
From what I can understand, it was a part of the "design" in earlier versions of macOS, like Yosemite: https://support.apple.com/kb/PH18394?locale=en_US

Since soft/rounded effect is so 2010 these days, hardness and high contrast is the current fashion and thus things like transparency must go. My guess is that your screenshot is from an earlier version of macOS.

**Comment by Sami32** [comment]
Maybe. The macOS configuration used have transparency enable so it doesn't come from that.
I guess that a test with the same Oracle Virtualbox software will give the answer.

**Comment by Nadahar** [comment]
I don't think the virtualization server makes any difference, do you have a reference to which macOS version is used for the screenshot?

**Comment by Sami32** [comment]
Only that this image was posted in 2013.
It seem that the latest Oracle VirtualBox package doesn't show any transparency so that could be as you said.

**Comment by gino0631** [comment]
Just for completeness - this is how it looks like on macOS High Sierra: 
![screen shot 2018-07-19 at 05 38 21](https://user-images.githubusercontent.com/13659309/42918500-fbe8c8be-8b05-11e8-8d99-2c8fd459d467.png)
